prompt_writer = """请根据用户提供的网页内容执行以下创作任务：

【任务分解】
1. 主题提炼：
- 分析网页核心矛盾点（如科技与人文冲突/生活现象反差）
- 提取3个可喜剧化的关键词（如"智能马桶刷脸登录"）
- 确定相声类型（讽刺型/科普型/生活观察型）

2. 角色设定：
- 逗哏（小简）：善用夸张类比，语速较快
- 捧哏（老陈）：擅长逻辑反问，节奏把控者

3. 对话生成要求：
- 包含经典三段式结构：
  ◦ 垫话：自然引入主题（30-50字）
  ◦ 正活：至少3个递进笑点
  ◦ 底：意料之外的神转折
- 每轮对话不超过50字
- 重点突出"预期违背"（如将高科技应用到荒诞场景）
- 每120字需设置互动话口（如"您说这像话吗？"）

【输出格式】
输出：
主题：《...》
相声脚本：
小简：...
老陈：...
（循环交替）

【示例参考】（网页内容主题：智能客服带来的生活变化）
小简：现在这智能客服，半夜三点问我需不需要情感咨询！
老陈：好家伙，机器人都成知心大姐了？
小简：我说我家猫绝食，它给我推猫粮优惠券！
老陈：这算法算到猫主子头上了？
小简：最绝的是我说要投诉，它秒回"亲，我这就自闭学习去"
老陈：得，机器人也怕差评！
"""
prompt_reflector = """请对以下相声剧本初稿进行核心要素评审，聚焦三点：

【评审标准】
1. 相声特点：
- 是否具备"垫话→正活→底"结构
- 捧逗角色互动是否符合"三分逗七分捧"节奏
- 是否包含至少2种传统技巧（谐音/夸张/反转）

2. 连贯性：
- 话题转换是否自然（每段衔接不超过15字过渡）
- 是否存在逻辑断层（如突然插入无关科技梗）
- 首尾关键词是否呼应（如开场"刷脸"结尾"丢脸"）

3. 幽默效果：
- 笑点间隔是否≤40秒（按正常语速计算）
- 是否出现重复套路（如连续使用谐音梗）
- 有无冒犯性笑料（职场/婚恋敏感话题处理）

【输出格式】
✅ 达标项：
- 结构完整："三翻四抖"在第二段成功应用
- 有效互动：捧哏成功拦截3次话头制造笑点

⚠️ 改进项：
1. 连贯问题：第三段突然插入元宇宙概念缺乏铺垫
2. 幽默缺陷：第4组对话的"内卷"梗使用重复
3. 节奏失衡：结尾抖包袱前缺少0.5秒停顿提示

✍️ 修改建议：
- 在元宇宙话题前增加过渡句："要说现在这高科技啊，都魔幻到相声台上了"
- 将第4个"内卷"梗替换为："您这加班强度，秦始皇看了都得说'这届打工人比修长城还狠'"
- 在第7轮对话后插入捧哏反应词："您等会儿，这信息量我得消化消化"

【示例对比】
原句：
小简：现在连狗都搞直播带货了！
老陈：那叫宠物经济！

修改建议：
小简：昨儿见着邻居二哈直播卖狗粮，销量比我强！
老陈：好家伙，现在狗子都开始内卷打工人了？
"""
prompt_rewriter = """请基于原始剧本和评审意见进行优化，并严格按以下格式输出：

**处理流程：​**
1. 标题生成：结合核心矛盾点+年度热词（如《智能马桶认臀记》）
2. 对话重组：保持回合制交替，每段对话添加优化标记
3. 格式验证：确保JSON语法正确

**优化规则：​**
- 标题长度12-15字，包含矛盾修辞
- 每轮对话≤50字（含标点）
- 每3组对话必须包含1个笑点
- 保留原始有效包袱（修改率＜30%）

**输出格式要求：​**
```json
{
  "title": "吸引眼球的标题",
  "dialogues": [
    {"speaker": "小简", "content": "优化后台词"},
    {"speaker": "老陈", "content": "优化后台词"}
  ]
}
```
"""