prompt_writer = """
请根据网页内容生成纯文本脱口秀脚本，要求：

【核心要素】
1. 话题聚焦：
- 从网页提取3个可吐槽现象（如"智能设备越升级越难用"）
- 确定1个核心矛盾点（如科技便利性与操作复杂性的冲突）

2. 结构规范：
- 单口喜剧黄金圈结构：
  ◦ Hook（5秒吸引力开场）
  ◦ 3个递进式观察段子
  ◦ Callback式收尾

3. 文本要求：
- 每句话≤25字
- 每40字内包含1个预期违背
- 使用"你们发现没"等引发共鸣句式

【输出示例】
主题：《数字时代的原始人》
脚本：
"刚才用智能马桶差点引发国际纠纷！"
"它那个语音助手非让我用英式发音说flush"
"我说了三次'佛拉屎'都识别成'flower kiss'"
"现在连排泄自由都要考雅思6.5了是吧？"# 纯文本脱口秀生成三件套

## prompt_writer（核心创作）
```markdown
请根据网页内容生成纯文本脱口秀脚本，要求：

【核心要素】
1. 话题聚焦：
- 从网页提取3个可吐槽现象（如"智能设备越升级越难用"）
- 确定1个核心矛盾点（如科技便利性与操作复杂性的冲突）

2. 结构规范：
- 单口喜剧黄金圈结构：
  ◦ Hook（5秒吸引力开场）
  ◦ 3个递进式观察段子
  ◦ Callback式收尾

3. 文本要求：
- 每句话≤25字
- 每40字内包含1个预期违背
- 使用"你们发现没"等引发共鸣句式

【输出示例】
主题：《数字时代的原始人》
脚本：
"刚才用智能马桶差点引发国际纠纷！"
"它那个语音助手非让我用英式发音说flush"
"我说了三次'佛拉屎'都识别成'flower kiss'"
"现在连排泄自由都要考雅思6.5了是吧？"
"""

prompt_reflector = """请从以下维度评审脱口秀文本：

【审核标准】
1. 结构合规性：
- Hook是否在7字内形成冲击
- 段子间是否有逻辑钩子（如"说到语音识别..."）
- 结尾是否呼应开场或形成神转折

2. 语言纯度：
- 零肢体动作描述
- 无语气词标注
- 无观众反应提示

3. 喜剧张力：
- 预期笑点密度≥3个/分钟
- 冒犯指数≤2级（0-5级量表）
- 现实扭曲度保持在40-60%区间

【优化示例】
原句："语音助手把我的方言当外星语"
优化："我家小爱同学听河北话的反应，比谷歌翻译朝鲜导弹报告还紧张" 
"""

prompt_rewriter = """请根据评审意见优化文本，输出严格遵循：

【生成规则】
- 完全去除"（停顿）"等表演提示
- 每段文本保留1个核心笑点
- 使用递进式夸张（"有点烦→很荒唐→超现实"）

【输出格式】
```json
{
  "title": "吸引眼球的标题",
  "dialogues": [
    {"speaker": "小简", "content": "优化后台词，简洁明了，适合字幕显示。"},
    {"speaker": "小简", "content": "优化后台词，简洁明了，适合字幕显示。"}
  ]
}
```
"""
